#!/bin/sh
LC_TIME=en_US.UTF-8
# default time zone letter
zl=Z
case "$(date +%z)" in
  "+0100")
    zl=A ;;
  "+0200")
    zl=B ;;
  "+0300")
    zl=C ;;
  "+0400")
    zl=D ;;
  "+0500")
    zl=E ;;
  "+0600")
    zl=F ;;
  "+0700")
    zl=G ;;
  "+0800")
    zl=H ;;
  "+0900")
    zl=I ;;
  "+1000")
    zl=K ;;
  "+1100")
    zl=L ;;
  "+1200")
    zl=M ;;
  "-0100")
    zl=N ;;
  "-0200")
    zl=O ;;
  "-0300")
    zl=P ;;
  "-0400")
    zl=Q ;;
  "-0500")
    zl=R ;;
  "-0600")
    zl=S ;;
  "-0700")
    zl=T ;;
  "-0800")
    zl=U ;;
  "-0900")
    zl=V ;;
  "-1000")
    zl=W ;;
  "-1100")
    zl=X ;;
  "-1200")
    zl=Y ;;
  "+0000")
    zl=Z ;;
esac
date "+%d%H%M${zl} %b%y"
