---
- name: "install dependencies to build wsjtx on armhf/raspberrypi"
  hosts: all
  gather_facts: no
  user: pi
  tasks:
  - name: install packages
    become: true
    apt:
      state: latest
      name:
      - vim
      - screen
      - cmake
      - automake
      - libtool
      - asciidoctor
      - asciidoc
      - gfortran
      - libwxgtk3.0-dev
      - libusb-1.0-0-dev
      - portaudio19-dev
      - libsamplerate0-dev
      - libasound2-dev
      - libao-dev
      - libfftw3-dev
      - libgsm1-dev
      - libjpeg9-dev
      - libxft-dev
      - libxinerama-dev
      - libxcursor-dev
      - libboost-all-dev
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - libqt5multimediaquick5
      - libqt5multimediawidgets5
      - libqt5serialport5-dev
      - libqt5svg5-dev
      - libqt5widgets5
      - libqt5sql5-sqlite
      - libqwt-qt5-dev
      - libsndfile1-dev
      - libudev-dev
      - qtmultimedia5-dev
      - texinfo
      - xsltproc
      - swig

